import type { Metadata } from "next";
import localFont from "next/font/local";

import { Toaster } from "@/components/ui/sonner";
import { QueryProvider } from "@/components/query-provider";

import "./globals.css";

const mySans = localFont({
  src: "./fonts/AlimamaFangYuanTiVF-Thin.woff2",
  variable: "--my-font",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "熊熊助手",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="zh-cn">
      <body className={`${mySans.variable} antialiased`}>
        <Toaster />
        <QueryProvider>{children}</QueryProvider>
      </body>
    </html>
  );
}
